INSERT INTO system_configs (config_key, config_value, description) VALUES
('withdraw_usdt_min',            '5',      'USDT 最低提币金额'),
('withdraw_usdt_max',            '50000',  'USDT 单笔提币上限'),
('withdraw_usdt_daily_max',      '100000', 'USDT 单日提币上限'),
('withdraw_usdt_fee',            '1',      'USDT 提币手续费/笔'),
('withdraw_usdt_auto_threshold', '1000',   'USDT 自动审核阈值 (低于此金额自动通过)'),
('withdraw_trx_min',             '50',     'TRX 最低提币金额'),
('withdraw_trx_max',             '500000', 'TRX 单笔提币上限'),
('withdraw_trx_fee',             '1',      'TRX 提币手续费/笔'),
('withdraw_cny_min',             '100',    'CNY 最低提现金额'),
('withdraw_cny_daily_max',       '50000',  'CNY 单日提现上限'),
('transfer_usdt_min',            '0.01',   '转账最低金额 (USDT)'),
('exchange_min_usdt',            '10',     '闪兑最低 USDT'),
('exchange_min_cny',             '10',     '闪兑最低 CNY'),
('exchange_min_trx',             '100',    '闪兑最低 TRX'),
('finance_min',                  '10',     '余额宝最低买入金额 (USDT)'),
('finance_max',                  '500000', '余额宝最高买入金额 (USDT)'),
('finance_annual_rate',          '8',      '余额宝年化利率 (%)'),
('pin_max_fail',                 '5',      'PIN 最大连续失败次数'),
('pin_lock_minutes',             '30',     'PIN 锁定时长 (分钟)'),
('redpacket_expire_hours',       '24',     '红包过期时间 (小时)'),
('deposit_confirmations',        '3',      '链上充值需要的确认数'),
('admin_telegram_id',            '',       '管理员 Telegram ID'),
('support_url',                  '',       '客服链接'),
('trading_group_url',            '',       '官方交易群链接'),
('game_center_url',              '',       '游戏中心链接'),
('maintenance_mode',             '0',      '维护模式开关 (0:关闭 1:开启)');
